### ISSUE TITLE
Find a nice way to extract images that should be used across different widgets.

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology-manifest#2]
Probably they belong in the manifest.

**Comment by mhelvens** [comment]
This includes icons shown in nested resource editor.

Maybe use data urls.

**Comment by mhelvens** [comment]
Data URI's:

https://css-tricks.com/data-uris/

They have advantages and disadvantages, and it's hard to know how performance and development convenience would pan out. Our options are roughly:

* Use hosted images files and store simple hrefs to them in the manifest, or
* Use data-uris.

Our solution is to use WebPack loaders. The manifest will simply use `require('./img/image.png')`, and then we can easily switch back-and-forth between corresponding loaders:

* https://github.com/webpack-contrib/file-loader
* https://github.com/webpack-contrib/url-loader

The `url-loader` even accepts a size-limit that auto-defaults to `file-loader`.

I will close this issue after putting Natallia's icons from open-physiology/open-physiology-apps.

**Comment by albatros13** [comment]
Server fails to load the new version of model library because of image-related issues:
 
ERROR in ./~/open-physiology-model/src/modules/icons/type.png
Module parse failed: C:\Users\Natallia\WebstormProjects\lyph-server\node_modules\babel-loader\lib\index.js!C:\Users\Natallia\WebstormProjects\lyph-server\node_modules\open-physiology-model\src\modules\icons\type.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)

**Comment by mhelvens** [comment]
Ah, of course. You're importing it from the original ES6 code. But it's not _just_ ES6 code; it also contains things like `require('lyph.png')`, which have to go through webpack before they make any sense.

You could configure your own webpack to handle .png files, but it's not really modular to require you to do that. I guess I'll have to provide a partially-compiled version.

PS: It would help if you stored all icons in standard icon-size. Some of them are huge, and that means we can't efficiently encode them with data-urls.

**Comment by albatros13** [comment]
This is an issue with server that does not use icons at all, I import model
library as before, but it does not work anymore, maybe there should be a
way to get access to the model classes without importing images if we dont
need them.

**Comment by mhelvens** [comment]
Could you convert each of the icons to a standard small size? That way, I could just encode them as data-urls and put them in. No more trouble.

Some of them are currently too large for that.

**Comment by albatros13** [comment]
How do I access images supplied by model library from GUI?

**Comment by mhelvens** [comment]
They're data-urls. So just use them as the 'src' of an <img> tag.

-- 
www.mhelvens.net
